name: 'Branch Action - Regular - GitHub Scripts'
description: 'Runs script from .github/scripts via branch-ref action'
runs:
  using: 'composite'
  steps:
    - run: bash .github/scripts/moved/action-branch-regular.sh
      shell: bash
