# PR-modified: added by test branch
name: 'Test: Reusable + Relative Action + GitHub Scripts'

on:
  pull_request:

jobs:
  call-reusable:
    uses: ./.github/workflows/test-reusable-relative-action-github-scripts.yml
