name: 'Test: Regular + Direct + CI Scripts'

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script directly
        run: bash ci/moved/direct-regular.sh
