name: 'Test: Regular + Direct + GitHub Scripts'

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script directly
        run: bash .github/scripts/direct-regular.sh # PR modified this line
